Libraries - fix some warnings with gcc ≥12 (#9244)
* ESP8266WebServer - unused templated code throws out unused statics

currently, only w/ mock build because it is using gcc>=12

> ../../libraries/ESP8266WebServer/src/detail/RequestHandlersImpl.h:14:15: warning: ‘String esp8266webserver::calcETag(fs::FS&, const String&)’ defined but not used [-Wunused-function]
>   14 | static String calcETag(FS &fs, const String &path) {
>      |               ^~~~~~~~

* ESP8266WiFiMesh - fix classes used as aggregates

> error: designated initializers cannot be used with a non-aggregate type '...'

gcc10.3 allowed this construct for some reason

* LEAmDNS - consistent const <-> non-const accessors

> error: infinite recursion detected [-Werror=infinite-recursion]