Fix case-insensitive ESPDuino file name
I work on Linux and I got an error about a missing `pins_arduino.h`:
```
fatal error: pins_arduino.h: No such file or directory
```
As it turns out, the reason for this is that the directory name under Linux is case-sensitive while it is lowercase-only in the variants file.